-- | The image object
module OpenAI.V1.Images.Image
    ( -- * Types
      ImageObject(..)
    ) where

import OpenAI.Prelude

-- | Represents the url or the content of an image generated by the OpenAI API
data ImageObject = ImageObject
    { b64_json :: Maybe Text
    , url :: Maybe Text
    , revised_prompt :: Maybe Text
    } deriving stock (Generic, Show)
      deriving anyclass (FromJSON, ToJSON)
